# Generated by Django 5.0.3 on 2024-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
    ]
