# Generated by Django 5.0.3 on 2024-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0003_task_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
