# Generated by Django 5.0.3 on 2024-03-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0005_group_tasklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Todo_app.tasklist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="Todo_app.group"
            ),
        ),
    ]
