# Generated by Django 5.0.3 on 2024-03-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0006_task_task_list_alter_tasklist_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Todo_app.tasklist",
            ),
        ),
    ]
