# Generated by Django 5.0.3 on 2024-03-09 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0007_alter_task_task_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Todo_app.tasklist",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Todo_app.group",
            ),
        ),
    ]
