# Generated by Django 5.0.3 on 2024-03-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo_app", "0008_alter_task_task_list_alter_tasklist_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Todo_app.group",
            ),
        ),
    ]
